name: Generate Pages
on:
  push:
    branches:
      - master
jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'CptWesley'
          git config --global user.email 'CptWesley@users.noreply.github.com'

      - name: Setup branch
        run: |
          git fetch
          git branch -f github-pages origin/master
          git checkout github-pages
          git branch --set-upstream-to origin/github-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Build
        run: npm run build
        working-directory: ./

      - name: Prepare directory
        run: |
          cp -a ./dist/. ./
          ln -s ./index.html ./404.html

      - name: Push webpage
        run: |
          git add -f ./
          git commit -am "Automated webpage deployment"
          git push -f -u origin
