name: Generate Pages
on:
  push:
    branches:
      - master
jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'CptWesley'
          git config --global user.email 'CptWesley@users.noreply.github.com'

      - name: Setup branch
        run: |
          git fetch
          git branch -f github-pages origin/master
          git checkout github-pages
          git branch --set-upstream-to origin/github-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./app/yarn.lock

      - name: Install dependencies
        run: yarn install
        working-directory: ./app

      - name: Build
        run: yarn generate
        working-directory: ./app

      - name: Prepare directory
        run: |
          git rm -r ./.github/
          git rm ./.gitignore
          git rm -r *
          cp -a ./app/.output/public/. ./
          rm -r ./app/

      - name: Push webpage
        run: |
          git add -f ./
          git commit -am "Automated webpage deployment"
          git push -f -u origin
